from abc import ABC


class Callback(ABC):
    
    def on_train_begin(self, model, logs=None): ...

    def on_train_end(self, model, logs=None)

    def on_train_epoch_begin(self, model, logs=None): ...

    def on_train_epoch_end(self, model, logs=None): ...

    def on_train_batch_begin(self, model, logs=None): ...

    def on_train_batch_end(self, model, logs=None): ...

    def on_validation_begin(self, model, logs=None): ...

    def on_validation_end(self, model, logs=None): ...

    def on_validation_batch_begin(self, model, logs=None): ...

    def on_validation_batch_end(self, model, logs=None): ...